import { NextResponse } from 'next/server';
import { readFile } from '@/lib/storage';

/**
 * Phase-8C — public file-serve endpoint for post cover images (and any
 * future inline post images). No auth — these are intentionally
 * world-readable, just like /og.png or /logo.png.
 *
 * Filenames are random hex generated by storage.ts; safePath() inside
 * readFile() blocks any path traversal attempt.
 */

const MIME_BY_EXT: Record<string, string> = {
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  png: 'image/png',
  webp: 'image/webp',
};

export async function GET(_req: Request, { params }: { params: { name: string } }) {
  const ext = params.name.split('.').pop()?.toLowerCase() ?? '';
  const mime = MIME_BY_EXT[ext];
  if (!mime) {
    return NextResponse.json({ error: 'Unsupported type' }, { status: 400 });
  }

  try {
    const buffer = await readFile(params.name);
    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        'Content-Type': mime,
        // Browser cache for a day; immutable filename means a new upload
        // gets a new URL so we can be aggressive.
        'Cache-Control': 'public, max-age=86400, immutable',
      },
    });
  } catch {
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }
}
